<?php

declare(strict_types=1);

/**
 * ISO 3166-1 alpha-2 country catalog (code => localized names).
 * Names are sourced from ICU and kept in-repo so validation does not depend on the runtime locale data.
 *
 * @return array<string, array{en: string, ar: string}>
 */
return [
    'AD' => ['en' => 'Andorra', 'ar' => 'أندورا'],
    'AE' => ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة'],
    'AF' => ['en' => 'Afghanistan', 'ar' => 'أفغانستان'],
    'AG' => ['en' => 'Antigua & Barbuda', 'ar' => 'أنتيغوا وبربودا'],
    'AI' => ['en' => 'Anguilla', 'ar' => 'أنغويلا'],
    'AL' => ['en' => 'Albania', 'ar' => 'ألبانيا'],
    'AM' => ['en' => 'Armenia', 'ar' => 'أرمينيا'],
    'AO' => ['en' => 'Angola', 'ar' => 'أنغولا'],
    'AQ' => ['en' => 'Antarctica', 'ar' => 'أنتاركتيكا'],
    'AR' => ['en' => 'Argentina', 'ar' => 'الأرجنتين'],
    'AS' => ['en' => 'American Samoa', 'ar' => 'ساموا الأمريكية'],
    'AT' => ['en' => 'Austria', 'ar' => 'النمسا'],
    'AU' => ['en' => 'Australia', 'ar' => 'أستراليا'],
    'AW' => ['en' => 'Aruba', 'ar' => 'أروبا'],
    'AX' => ['en' => 'Åland Islands', 'ar' => 'جزر آلاند'],
    'AZ' => ['en' => 'Azerbaijan', 'ar' => 'أذربيجان'],
    'BA' => ['en' => 'Bosnia & Herzegovina', 'ar' => 'البوسنة والهرسك'],
    'BB' => ['en' => 'Barbados', 'ar' => 'بربادوس'],
    'BD' => ['en' => 'Bangladesh', 'ar' => 'بنغلاديش'],
    'BE' => ['en' => 'Belgium', 'ar' => 'بلجيكا'],
    'BF' => ['en' => 'Burkina Faso', 'ar' => 'بوركينا فاسو'],
    'BG' => ['en' => 'Bulgaria', 'ar' => 'بلغاريا'],
    'BH' => ['en' => 'Bahrain', 'ar' => 'البحرين'],
    'BI' => ['en' => 'Burundi', 'ar' => 'بوروندي'],
    'BJ' => ['en' => 'Benin', 'ar' => 'بنين'],
    'BL' => ['en' => 'St. Barthélemy', 'ar' => 'سان بارتليمي'],
    'BM' => ['en' => 'Bermuda', 'ar' => 'برمودا'],
    'BN' => ['en' => 'Brunei', 'ar' => 'بروناي'],
    'BO' => ['en' => 'Bolivia', 'ar' => 'بوليفيا'],
    'BQ' => ['en' => 'Caribbean Netherlands', 'ar' => 'هولندا الكاريبية'],
    'BR' => ['en' => 'Brazil', 'ar' => 'البرازيل'],
    'BS' => ['en' => 'Bahamas', 'ar' => 'جزر البهاما'],
    'BT' => ['en' => 'Bhutan', 'ar' => 'بوتان'],
    'BV' => ['en' => 'Bouvet Island', 'ar' => 'جزيرة بوفيه'],
    'BW' => ['en' => 'Botswana', 'ar' => 'بوتسوانا'],
    'BY' => ['en' => 'Belarus', 'ar' => 'بيلاروس'],
    'BZ' => ['en' => 'Belize', 'ar' => 'بليز'],
    'CA' => ['en' => 'Canada', 'ar' => 'كندا'],
    'CC' => ['en' => 'Cocos (Keeling) Islands', 'ar' => 'جزر كوكوس (كيلينغ)'],
    'CD' => ['en' => 'Congo - Kinshasa', 'ar' => 'الكونغو - كينشاسا'],
    'CF' => ['en' => 'Central African Republic', 'ar' => 'جمهورية أفريقيا الوسطى'],
    'CG' => ['en' => 'Congo - Brazzaville', 'ar' => 'الكونغو - برازافيل'],
    'CH' => ['en' => 'Switzerland', 'ar' => 'سويسرا'],
    'CI' => ['en' => 'Côte d’Ivoire', 'ar' => 'ساحل العاج'],
    'CK' => ['en' => 'Cook Islands', 'ar' => 'جزر كوك'],
    'CL' => ['en' => 'Chile', 'ar' => 'تشيلي'],
    'CM' => ['en' => 'Cameroon', 'ar' => 'الكاميرون'],
    'CN' => ['en' => 'China', 'ar' => 'الصين'],
    'CO' => ['en' => 'Colombia', 'ar' => 'كولومبيا'],
    'CR' => ['en' => 'Costa Rica', 'ar' => 'كوستاريكا'],
    'CU' => ['en' => 'Cuba', 'ar' => 'كوبا'],
    'CV' => ['en' => 'Cape Verde', 'ar' => 'الرأس الأخضر'],
    'CW' => ['en' => 'Curaçao', 'ar' => 'كوراساو'],
    'CX' => ['en' => 'Christmas Island', 'ar' => 'جزيرة كريسماس'],
    'CY' => ['en' => 'Cyprus', 'ar' => 'قبرص'],
    'CZ' => ['en' => 'Czechia', 'ar' => 'التشيك'],
    'DE' => ['en' => 'Germany', 'ar' => 'ألمانيا'],
    'DJ' => ['en' => 'Djibouti', 'ar' => 'جيبوتي'],
    'DK' => ['en' => 'Denmark', 'ar' => 'الدانمرك'],
    'DM' => ['en' => 'Dominica', 'ar' => 'دومينيكا'],
    'DO' => ['en' => 'Dominican Republic', 'ar' => 'جمهورية الدومينيكان'],
    'DZ' => ['en' => 'Algeria', 'ar' => 'الجزائر'],
    'EC' => ['en' => 'Ecuador', 'ar' => 'الإكوادور'],
    'EE' => ['en' => 'Estonia', 'ar' => 'إستونيا'],
    'EG' => ['en' => 'Egypt', 'ar' => 'مصر'],
    'EH' => ['en' => 'Western Sahara', 'ar' => 'الصحراء الغربية'],
    'ER' => ['en' => 'Eritrea', 'ar' => 'إريتريا'],
    'ES' => ['en' => 'Spain', 'ar' => 'إسبانيا'],
    'ET' => ['en' => 'Ethiopia', 'ar' => 'إثيوبيا'],
    'FI' => ['en' => 'Finland', 'ar' => 'فنلندا'],
    'FJ' => ['en' => 'Fiji', 'ar' => 'فيجي'],
    'FK' => ['en' => 'Falkland Islands', 'ar' => 'جزر فوكلاند'],
    'FM' => ['en' => 'Micronesia', 'ar' => 'ميكرونيزيا'],
    'FO' => ['en' => 'Faroe Islands', 'ar' => 'جزر فارو'],
    'FR' => ['en' => 'France', 'ar' => 'فرنسا'],
    'GA' => ['en' => 'Gabon', 'ar' => 'الغابون'],
    'GB' => ['en' => 'United Kingdom', 'ar' => 'المملكة المتحدة'],
    'GD' => ['en' => 'Grenada', 'ar' => 'غرينادا'],
    'GE' => ['en' => 'Georgia', 'ar' => 'جورجيا'],
    'GF' => ['en' => 'French Guiana', 'ar' => 'غويانا الفرنسية'],
    'GG' => ['en' => 'Guernsey', 'ar' => 'غيرنزي'],
    'GH' => ['en' => 'Ghana', 'ar' => 'غانا'],
    'GI' => ['en' => 'Gibraltar', 'ar' => 'جبل طارق'],
    'GL' => ['en' => 'Greenland', 'ar' => 'غرينلاند'],
    'GM' => ['en' => 'Gambia', 'ar' => 'غامبيا'],
    'GN' => ['en' => 'Guinea', 'ar' => 'غينيا'],
    'GP' => ['en' => 'Guadeloupe', 'ar' => 'غوادلوب'],
    'GQ' => ['en' => 'Equatorial Guinea', 'ar' => 'غينيا الاستوائية'],
    'GR' => ['en' => 'Greece', 'ar' => 'اليونان'],
    'GS' => ['en' => 'South Georgia & South Sandwich Islands', 'ar' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'],
    'GT' => ['en' => 'Guatemala', 'ar' => 'غواتيمالا'],
    'GU' => ['en' => 'Guam', 'ar' => 'غوام'],
    'GW' => ['en' => 'Guinea-Bissau', 'ar' => 'غينيا بيساو'],
    'GY' => ['en' => 'Guyana', 'ar' => 'غيانا'],
    'HK' => ['en' => 'Hong Kong SAR China', 'ar' => 'هونغ كونغ الصينية (منطقة إدارية خاصة)'],
    'HM' => ['en' => 'Heard & McDonald Islands', 'ar' => 'جزيرة هيرد وجزر ماكدونالد'],
    'HN' => ['en' => 'Honduras', 'ar' => 'هندوراس'],
    'HR' => ['en' => 'Croatia', 'ar' => 'كرواتيا'],
    'HT' => ['en' => 'Haiti', 'ar' => 'هايتي'],
    'HU' => ['en' => 'Hungary', 'ar' => 'هنغاريا'],
    'ID' => ['en' => 'Indonesia', 'ar' => 'إندونيسيا'],
    'IE' => ['en' => 'Ireland', 'ar' => 'أيرلندا'],
    'IM' => ['en' => 'Isle of Man', 'ar' => 'جزيرة مان'],
    'IN' => ['en' => 'India', 'ar' => 'الهند'],
    'IO' => ['en' => 'British Indian Ocean Territory', 'ar' => 'الإقليم البريطاني في المحيط الهندي'],
    'IQ' => ['en' => 'Iraq', 'ar' => 'العراق'],
    'IR' => ['en' => 'Iran', 'ar' => 'إيران'],
    'IS' => ['en' => 'Iceland', 'ar' => 'آيسلندا'],
    'IT' => ['en' => 'Italy', 'ar' => 'إيطاليا'],
    'JE' => ['en' => 'Jersey', 'ar' => 'جيرسي'],
    'JM' => ['en' => 'Jamaica', 'ar' => 'جامايكا'],
    'JO' => ['en' => 'Jordan', 'ar' => 'الأردن'],
    'JP' => ['en' => 'Japan', 'ar' => 'اليابان'],
    'KE' => ['en' => 'Kenya', 'ar' => 'كينيا'],
    'KG' => ['en' => 'Kyrgyzstan', 'ar' => 'قيرغيزستان'],
    'KH' => ['en' => 'Cambodia', 'ar' => 'كمبوديا'],
    'KI' => ['en' => 'Kiribati', 'ar' => 'كيريباتي'],
    'KM' => ['en' => 'Comoros', 'ar' => 'جزر القمر'],
    'KN' => ['en' => 'St. Kitts & Nevis', 'ar' => 'سانت كيتس ونيفيس'],
    'KP' => ['en' => 'North Korea', 'ar' => 'كوريا الشمالية'],
    'KR' => ['en' => 'South Korea', 'ar' => 'كوريا الجنوبية'],
    'KW' => ['en' => 'Kuwait', 'ar' => 'الكويت'],
    'KY' => ['en' => 'Cayman Islands', 'ar' => 'جزر كايمان'],
    'KZ' => ['en' => 'Kazakhstan', 'ar' => 'كازاخستان'],
    'LA' => ['en' => 'Laos', 'ar' => 'لاوس'],
    'LB' => ['en' => 'Lebanon', 'ar' => 'لبنان'],
    'LC' => ['en' => 'St. Lucia', 'ar' => 'سانت لوسيا'],
    'LI' => ['en' => 'Liechtenstein', 'ar' => 'ليختنشتاين'],
    'LK' => ['en' => 'Sri Lanka', 'ar' => 'سريلانكا'],
    'LR' => ['en' => 'Liberia', 'ar' => 'ليبيريا'],
    'LS' => ['en' => 'Lesotho', 'ar' => 'ليسوتو'],
    'LT' => ['en' => 'Lithuania', 'ar' => 'ليتوانيا'],
    'LU' => ['en' => 'Luxembourg', 'ar' => 'لوكسمبورغ'],
    'LV' => ['en' => 'Latvia', 'ar' => 'لاتفيا'],
    'LY' => ['en' => 'Libya', 'ar' => 'ليبيا'],
    'MA' => ['en' => 'Morocco', 'ar' => 'المغرب'],
    'MC' => ['en' => 'Monaco', 'ar' => 'موناكو'],
    'MD' => ['en' => 'Moldova', 'ar' => 'مولدوفا'],
    'ME' => ['en' => 'Montenegro', 'ar' => 'الجبل الأسود'],
    'MF' => ['en' => 'St. Martin', 'ar' => 'سان مارتن'],
    'MG' => ['en' => 'Madagascar', 'ar' => 'مدغشقر'],
    'MH' => ['en' => 'Marshall Islands', 'ar' => 'جزر مارشال'],
    'MK' => ['en' => 'North Macedonia', 'ar' => 'مقدونيا الشمالية'],
    'ML' => ['en' => 'Mali', 'ar' => 'مالي'],
    'MM' => ['en' => 'Myanmar (Burma)', 'ar' => 'ميانمار (بورما)'],
    'MN' => ['en' => 'Mongolia', 'ar' => 'منغوليا'],
    'MO' => ['en' => 'Macao SAR China', 'ar' => 'منطقة ماكاو الإدارية الخاصة'],
    'MP' => ['en' => 'Northern Mariana Islands', 'ar' => 'جزر ماريانا الشمالية'],
    'MQ' => ['en' => 'Martinique', 'ar' => 'جزر المارتينيك'],
    'MR' => ['en' => 'Mauritania', 'ar' => 'موريتانيا'],
    'MS' => ['en' => 'Montserrat', 'ar' => 'مونتسرات'],
    'MT' => ['en' => 'Malta', 'ar' => 'مالطا'],
    'MU' => ['en' => 'Mauritius', 'ar' => 'موريشيوس'],
    'MV' => ['en' => 'Maldives', 'ar' => 'جزر المالديف'],
    'MW' => ['en' => 'Malawi', 'ar' => 'ملاوي'],
    'MX' => ['en' => 'Mexico', 'ar' => 'المكسيك'],
    'MY' => ['en' => 'Malaysia', 'ar' => 'ماليزيا'],
    'MZ' => ['en' => 'Mozambique', 'ar' => 'موزمبيق'],
    'NA' => ['en' => 'Namibia', 'ar' => 'ناميبيا'],
    'NC' => ['en' => 'New Caledonia', 'ar' => 'كاليدونيا الجديدة'],
    'NE' => ['en' => 'Niger', 'ar' => 'النيجر'],
    'NF' => ['en' => 'Norfolk Island', 'ar' => 'جزيرة نورفولك'],
    'NG' => ['en' => 'Nigeria', 'ar' => 'نيجيريا'],
    'NI' => ['en' => 'Nicaragua', 'ar' => 'نيكاراغوا'],
    'NL' => ['en' => 'Netherlands', 'ar' => 'هولندا'],
    'NO' => ['en' => 'Norway', 'ar' => 'النرويج'],
    'NP' => ['en' => 'Nepal', 'ar' => 'نيبال'],
    'NR' => ['en' => 'Nauru', 'ar' => 'ناورو'],
    'NU' => ['en' => 'Niue', 'ar' => 'نيوي'],
    'NZ' => ['en' => 'New Zealand', 'ar' => 'نيوزيلندا'],
    'OM' => ['en' => 'Oman', 'ar' => 'عُمان'],
    'PA' => ['en' => 'Panama', 'ar' => 'بنما'],
    'PE' => ['en' => 'Peru', 'ar' => 'بيرو'],
    'PF' => ['en' => 'French Polynesia', 'ar' => 'بولينيزيا الفرنسية'],
    'PG' => ['en' => 'Papua New Guinea', 'ar' => 'بابوا غينيا الجديدة'],
    'PH' => ['en' => 'Philippines', 'ar' => 'الفلبين'],
    'PK' => ['en' => 'Pakistan', 'ar' => 'باكستان'],
    'PL' => ['en' => 'Poland', 'ar' => 'بولندا'],
    'PM' => ['en' => 'St. Pierre & Miquelon', 'ar' => 'سان بيير ومكويلون'],
    'PN' => ['en' => 'Pitcairn Islands', 'ar' => 'جزر بيتكيرن'],
    'PR' => ['en' => 'Puerto Rico', 'ar' => 'بورتوريكو'],
    'PS' => ['en' => 'Palestine', 'ar' => 'فلسطين'],
    'PT' => ['en' => 'Portugal', 'ar' => 'البرتغال'],
    'PW' => ['en' => 'Palau', 'ar' => 'بالاو'],
    'PY' => ['en' => 'Paraguay', 'ar' => 'باراغواي'],
    'QA' => ['en' => 'Qatar', 'ar' => 'قطر'],
    'RE' => ['en' => 'Réunion', 'ar' => 'روينيون'],
    'RO' => ['en' => 'Romania', 'ar' => 'رومانيا'],
    'RS' => ['en' => 'Serbia', 'ar' => 'صربيا'],
    'RU' => ['en' => 'Russia', 'ar' => 'روسيا'],
    'RW' => ['en' => 'Rwanda', 'ar' => 'رواندا'],
    'SA' => ['en' => 'Saudi Arabia', 'ar' => 'المملكة العربية السعودية'],
    'SB' => ['en' => 'Solomon Islands', 'ar' => 'جزر سليمان'],
    'SC' => ['en' => 'Seychelles', 'ar' => 'سيشل'],
    'SD' => ['en' => 'Sudan', 'ar' => 'السودان'],
    'SE' => ['en' => 'Sweden', 'ar' => 'السويد'],
    'SG' => ['en' => 'Singapore', 'ar' => 'سنغافورة'],
    'SH' => ['en' => 'St. Helena', 'ar' => 'سانت هيلينا'],
    'SI' => ['en' => 'Slovenia', 'ar' => 'سلوفينيا'],
    'SJ' => ['en' => 'Svalbard & Jan Mayen', 'ar' => 'سفالبارد وجان ماين'],
    'SK' => ['en' => 'Slovakia', 'ar' => 'سلوفاكيا'],
    'SL' => ['en' => 'Sierra Leone', 'ar' => 'سيراليون'],
    'SM' => ['en' => 'San Marino', 'ar' => 'سان مارينو'],
    'SN' => ['en' => 'Senegal', 'ar' => 'السنغال'],
    'SO' => ['en' => 'Somalia', 'ar' => 'الصومال'],
    'SR' => ['en' => 'Suriname', 'ar' => 'سورينام'],
    'SS' => ['en' => 'South Sudan', 'ar' => 'جنوب السودان'],
    'ST' => ['en' => 'São Tomé & Príncipe', 'ar' => 'ساو تومي وبرينسيبي'],
    'SV' => ['en' => 'El Salvador', 'ar' => 'السلفادور'],
    'SX' => ['en' => 'Sint Maarten', 'ar' => 'سانت مارتن'],
    'SY' => ['en' => 'Syria', 'ar' => 'سوريا'],
    'SZ' => ['en' => 'Eswatini', 'ar' => 'إسواتيني'],
    'TC' => ['en' => 'Turks & Caicos Islands', 'ar' => 'جزر توركس وكايكوس'],
    'TD' => ['en' => 'Chad', 'ar' => 'تشاد'],
    'TF' => ['en' => 'French Southern Territories', 'ar' => 'الأقاليم الجنوبية الفرنسية'],
    'TG' => ['en' => 'Togo', 'ar' => 'توغو'],
    'TH' => ['en' => 'Thailand', 'ar' => 'تايلاند'],
    'TJ' => ['en' => 'Tajikistan', 'ar' => 'طاجيكستان'],
    'TK' => ['en' => 'Tokelau', 'ar' => 'توكيلاو'],
    'TL' => ['en' => 'Timor-Leste', 'ar' => 'تيمور - ليشتي'],
    'TM' => ['en' => 'Turkmenistan', 'ar' => 'تركمانستان'],
    'TN' => ['en' => 'Tunisia', 'ar' => 'تونس'],
    'TO' => ['en' => 'Tonga', 'ar' => 'تونغا'],
    'TR' => ['en' => 'Türkiye', 'ar' => 'تركيا'],
    'TT' => ['en' => 'Trinidad & Tobago', 'ar' => 'ترينيداد وتوباغو'],
    'TV' => ['en' => 'Tuvalu', 'ar' => 'توفالو'],
    'TW' => ['en' => 'Taiwan', 'ar' => 'تايوان'],
    'TZ' => ['en' => 'Tanzania', 'ar' => 'تنزانيا'],
    'UA' => ['en' => 'Ukraine', 'ar' => 'أوكرانيا'],
    'UG' => ['en' => 'Uganda', 'ar' => 'أوغندا'],
    'UM' => ['en' => 'U.S. Outlying Islands', 'ar' => 'جزر الولايات المتحدة النائية'],
    'US' => ['en' => 'United States', 'ar' => 'الولايات المتحدة'],
    'UY' => ['en' => 'Uruguay', 'ar' => 'أورغواي'],
    'UZ' => ['en' => 'Uzbekistan', 'ar' => 'أوزبكستان'],
    'VA' => ['en' => 'Vatican City', 'ar' => 'الفاتيكان'],
    'VC' => ['en' => 'St. Vincent & Grenadines', 'ar' => 'سانت فنسنت وجزر غرينادين'],
    'VE' => ['en' => 'Venezuela', 'ar' => 'فنزويلا'],
    'VG' => ['en' => 'British Virgin Islands', 'ar' => 'جزر فيرجن البريطانية'],
    'VI' => ['en' => 'U.S. Virgin Islands', 'ar' => 'جزر فيرجن الأمريكية'],
    'VN' => ['en' => 'Vietnam', 'ar' => 'فيتنام'],
    'VU' => ['en' => 'Vanuatu', 'ar' => 'فانواتو'],
    'WF' => ['en' => 'Wallis & Futuna', 'ar' => 'جزر والس وفوتونا'],
    'WS' => ['en' => 'Samoa', 'ar' => 'ساموا'],
    'YE' => ['en' => 'Yemen', 'ar' => 'اليمن'],
    'YT' => ['en' => 'Mayotte', 'ar' => 'مايوت'],
    'ZA' => ['en' => 'South Africa', 'ar' => 'جنوب أفريقيا'],
    'ZM' => ['en' => 'Zambia', 'ar' => 'زامبيا'],
    'ZW' => ['en' => 'Zimbabwe', 'ar' => 'زيمبابوي'],
];
